# pylint: disable=missing-docstring
"""Added team_matches table

Revision ID: 11aa784195ef
Revises: 1dd5bda9df82
Create Date: 2021-04-10 23:38:39.387189

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "11aa784195ef"
down_revision = "1dd5bda9df82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("at_home", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_matches")
    # ### end Alembic commands ###
