# Generated by Django 2.1.4 on 2018-12-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20181228_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('start_date_time', 'venue')},
        ),
    ]
