# Generated by Django 3.0.2 on 2020-02-06 00:10

from django.db import migrations, models
import server.models.match


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190530_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='predicted_win_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_date_time',
            field=models.DateTimeField(validators=[server.models.match.validate_is_utc]),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_margin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
