# Generated by Django 3.0.5 on 2020-04-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200206_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='data_class_path',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='trained_to_match',
        ),
        migrations.AlterField(
            model_name='prediction',
            name='is_correct',
            field=models.BooleanField(null=True, blank=True),
        ),
    ]
