# Generated by Django 3.0.6 on 2020-05-30 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20200425_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='predicted_margin',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
