# Generated by Django 3.0.6 on 2020-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20200530_0737'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mlmodel',
            name='one_principle_model',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='is_principle',
            new_name='is_principal',
        ),
        migrations.AddConstraint(
            model_name='mlmodel',
            constraint=models.UniqueConstraint(condition=models.Q(is_principal=True), fields=('is_principal',), name='one_principal_model'),
        ),
    ]
