# Generated by Django 3.0.7 on 2020-06-14 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20200613_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
