// flow-typed signature: 7b1de8fe9cd970efbf149fcbdfff06d0
// flow-typed version: <<STUB>>/styled-components/macro_v^1.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components/macro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components/macro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-components/macro/macro' {
  declare module.exports: any;
}

declare module 'styled-components/macro/test/macro.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-components/macro/macro.js' {
  declare module.exports: $Exports<'styled-components/macro/macro'>;
}
declare module 'styled-components/macro/test/macro.test.js' {
  declare module.exports: $Exports<'styled-components/macro/test/macro.test'>;
}
