"""Module for data transformations and internal conventions"""

TEAM_TRANSLATIONS = {
    "Tigers": "Richmond",
    "Blues": "Carlton",
    "Demons": "Melbourne",
    "Giants": "GWS",
    "GWS Giants": "GWS",
    "Greater Western Sydney": "GWS",
    "Suns": "Gold Coast",
    "Bombers": "Essendon",
    "Swans": "Sydney",
    "Magpies": "Collingwood",
    "Kangaroos": "North Melbourne",
    "Crows": "Adelaide",
    "Bulldogs": "Western Bulldogs",
    "Footscray": "Western Bulldogs",
    "Dockers": "Fremantle",
    "Power": "Port Adelaide",
    "Saints": "St Kilda",
    "Eagles": "West Coast",
    "Lions": "Brisbane",
    "Cats": "Geelong",
    "Hawks": "Hawthorn",
    "Adelaide Crows": "Adelaide",
    "Brisbane Lions": "Brisbane",
    "Brisbane Bears": "Brisbane",
    "Gold Coast Suns": "Gold Coast",
    "Geelong Cats": "Geelong",
    "West Coast Eagles": "West Coast",
    "Sydney Swans": "Sydney",
}

# I used this dictionary to convert betting venue names to match venue names
# for the sake of joining the two data sets, but no longer use venues to join them.
# It was a pain to put this together, though, so I'm keeping it around in case I need
# it later.
# BETTING_VENUE_TRANSLATIONS = {
#     "AAMI": "AAMI Stadium",
#     "ANZ": "ANZ Stadium",
#     "Adelaide": "Adelaide Oval",
#     "Aurora": "UTAS Stadium",
#     "Aurora Stadium": "UTAS Stadium",
#     "Blacktown": "Blacktown International",
#     "Blundstone": "Blundstone Arena",
#     "Cazaly's": "Cazaly's Stadium",
#     "Domain": "Domain Stadium",
#     "Etihad": "Etihad Stadium",
#     "GMHBA": "GMHBA Stadium",
#     "Gabba": "Gabba",
#     "Jiangwan": "Jiangwan Stadium",
#     "MCG": "MCG",
#     "Mars": "Mars Stadium",
#     "Metricon": "Metricon Stadium",
#     "Perth": "Optus Stadium",
#     "SCG": "SCG",
#     "Spotless": "Spotless Stadium",
#     "StarTrack": "Manuka Oval",
#     "TIO": "TIO Stadium",
#     "UTAS": "UTAS Stadium",
#     "Westpac": "Westpac Stadium",
#     "TIO Traegar Park": "TIO Stadium",
# }

# For when we fetch upcoming matches in the fixture and need to make Footywire venue
# names consistent with AFL tables venue names
FOOTYWIRE_VENUE_TRANSLATIONS = {
    "AAMI Stadium": "Melbourne",
    "ANZ Stadium": "Stadium Australia",
    "UTAS Stadium": "York Park",
    "Blacktown International": "Blacktown",
    "Blundstone Arena": "Bellerive Oval",
    "Domain Stadium": "Subiaco",
    "Etihad Stadium": "Docklands",
    "GMHBA Stadium": "Kardinia Park",
    "MCG": "M.C.G.",
    "Mars Stadium": "Eureka Stadium",
    "Metricon Stadium": "Carrara",
    "Optus Stadium": "Perth Stadium",
    "SCG": "S.C.G.",
    "Spotless Stadium": "Sydney Showground",
    "Showground Stadium": "Sydney Showground",
    "TIO Stadium": "Marrara Oval",
    "Westpac Stadium": "Wellington",
    "Marvel Stadium": "Docklands",
    "Canberra Oval": "Manuka Oval",
}

CITIES = {
    "Adelaide": {"state": "SA", "lat": -34.9285, "long": 138.6007},
    "Sydney": {"state": "NSW", "lat": -33.8688, "long": 151.2093},
    "Melbourne": {"state": "VIC", "lat": -37.8136, "long": 144.9631},
    "Geelong": {"state": "VIC", "lat": -38.1499, "long": 144.3617},
    "Perth": {"state": "WA", "lat": -31.9505, "long": 115.8605},
    "Gold Coast": {"state": "QLD", "lat": -28.0167, "long": 153.4000},
    "Brisbane": {"state": "QLD", "lat": -27.4698, "long": 153.0251},
    "Launceston": {"state": "TAS", "lat": -41.4332, "long": 147.1441},
    "Canberra": {"state": "ACT", "lat": -35.2809, "long": 149.1300},
    "Hobart": {"state": "TAS", "lat": -42.8821, "long": 147.3272},
    "Darwin": {"state": "NT", "lat": -12.4634, "long": 130.8456},
    "Alice Springs": {"state": "NT", "lat": -23.6980, "long": 133.8807},
    "Wellington": {"state": "NZ", "lat": -41.2865, "long": 174.7762},
    "Euroa": {"state": "VIC", "lat": -36.7500, "long": 145.5667},
    "Yallourn": {"state": "VIC", "lat": -38.1803, "long": 146.3183},
    "Cairns": {"state": "QLD", "lat": -6.9186, "long": 145.7781},
    "Ballarat": {"state": "VIC", "lat": -37.5622, "long": 143.8503},
    "Shanghai": {"state": "CHN", "lat": 31.2304, "long": 121.4737},
    "Albury": {"state": "NSW", "lat": -36.0737, "long": 146.9135},
    "Townsville": {"state": "QLD", "lat": -19.2590, "long": 146.8169},
}

TEAM_CITIES = {
    "Adelaide": "Adelaide",
    "Brisbane": "Brisbane",
    "Carlton": "Melbourne",
    "Collingwood": "Melbourne",
    "Essendon": "Melbourne",
    "Fitzroy": "Melbourne",
    "Western Bulldogs": "Melbourne",
    "Fremantle": "Perth",
    "GWS": "Sydney",
    "Geelong": "Geelong",
    "Gold Coast": "Gold Coast",
    "Hawthorn": "Melbourne",
    "Melbourne": "Melbourne",
    "North Melbourne": "Melbourne",
    "Port Adelaide": "Adelaide",
    "Richmond": "Melbourne",
    "St Kilda": "Melbourne",
    "Sydney": "Sydney",
    "University": "Melbourne",
    "West Coast": "Perth",
}

VENUE_CITIES = {
    # AFL Tables venues
    "Football Park": "Adelaide",
    "S.C.G.": "Sydney",
    "Windy Hill": "Melbourne",
    "Subiaco": "Perth",
    "Moorabbin Oval": "Melbourne",
    "M.C.G.": "Melbourne",
    "Kardinia Park": "Geelong",
    "Victoria Park": "Melbourne",
    "Waverley Park": "Melbourne",
    "Princes Park": "Melbourne",
    "Western Oval": "Melbourne",
    "W.A.C.A.": "Perth",
    "Carrara": "Gold Coast",
    "Gabba": "Brisbane",
    "Docklands": "Melbourne",
    "York Park": "Launceston",
    "Manuka Oval": "Canberra",
    "Sydney Showground": "Sydney",
    "Adelaide Oval": "Adelaide",
    "Bellerive Oval": "Hobart",
    "Marrara Oval": "Darwin",
    "Traeger Park": "Alice Springs",
    "Perth Stadium": "Perth",
    "Stadium Australia": "Sydney",
    "Wellington": "Wellington",
    "Lake Oval": "Melbourne",
    "East Melbourne": "Melbourne",
    "Corio Oval": "Geelong",
    "Junction Oval": "Melbourne",
    "Brunswick St": "Melbourne",
    "Punt Rd": "Melbourne",
    "Glenferrie Oval": "Melbourne",
    "Arden St": "Melbourne",
    "Olympic Park": "Melbourne",
    "Yarraville Oval": "Melbourne",
    "Toorak Park": "Melbourne",
    "Euroa": "Euroa",
    "Coburg Oval": "Melbourne",
    "Brisbane Exhibition": "Brisbane",
    "North Hobart": "Hobart",
    "Bruce Stadium": "Canberra",
    "Yallourn": "Yallourn",
    "Cazaly's Stadium": "Cairns",
    "Eureka Stadium": "Ballarat",
    "Blacktown": "Sydney",
    "Jiangwan Stadium": "Shanghai",
    "Albury": "Albury",
    # Footywire venues
    "AAMI Stadium": "Melbourne",
    "ANZ Stadium": "Sydney",
    "UTAS Stadium": "Launceston",
    "Blacktown International": "Sydney",
    "Blundstone Arena": "Hobart",
    "Domain Stadium": "Perth",
    "Etihad Stadium": "Melbourne",
    "GMHBA Stadium": "Geelong",
    "MCG": "Melbourne",
    "Mars Stadium": "Ballarat",
    "Metricon Stadium": "Gold Coast",
    "Optus Stadium": "Perth",
    "SCG": "Sydney",
    "Spotless Stadium": "Sydney",
    "TIO Stadium": "Darwin",
    "Westpac Stadium": "Wellington",
    "Marvel Stadium": "Melbourne",
    "Canberra Oval": "Canberra",
    "Riverway Stadium": "Townsville",
}

DEFUNCT_TEAM_NAMES = ["Fitzroy", "University"]
TEAM_NAMES = sorted(DEFUNCT_TEAM_NAMES + list(set(TEAM_TRANSLATIONS.values())))
ROUND_TYPES = ["Finals", "Regular"]
VENUES = list(set(VENUE_CITIES.keys()))
INDEX_COLS = ["team", "year", "round_number"]
SEED = 42
AVG_SEASON_LENGTH = 23
CATEGORY_COLS = ["team", "oppo_team", "round_type", "venue"]

# TODO: The data refactor reordered the columns, which completely messed up
# predictions. I don't want to retrain the models, so I'll just use the original column
# list to make sure they're in the same order as before, and figure out a better
# solution later
ORIGINAL_COLUMNS = [
    "team",
    "oppo_team",
    "round_type",
    "venue",
    "win_odds",
    "line_odds",
    "oppo_win_odds",
    "oppo_line_odds",
    "betting_pred_win",
    "rolling_betting_pred_win_rate",
    "oppo_result",
    "oppo_betting_pred_win",
    "oppo_rolling_betting_pred_win_rate",
    "rolling_prev_match_kicks_sum",
    "rolling_prev_match_kicks_max",
    "rolling_prev_match_kicks_min",
    "rolling_prev_match_kicks_skew",
    "rolling_prev_match_kicks_std",
    "rolling_prev_match_marks_sum",
    "rolling_prev_match_marks_max",
    "rolling_prev_match_marks_min",
    "rolling_prev_match_marks_skew",
    "rolling_prev_match_marks_std",
    "rolling_prev_match_handballs_sum",
    "rolling_prev_match_handballs_max",
    "rolling_prev_match_handballs_min",
    "rolling_prev_match_handballs_skew",
    "rolling_prev_match_handballs_std",
    "rolling_prev_match_goals_sum",
    "rolling_prev_match_goals_max",
    "rolling_prev_match_goals_min",
    "rolling_prev_match_goals_skew",
    "rolling_prev_match_goals_std",
    "rolling_prev_match_behinds_sum",
    "rolling_prev_match_behinds_max",
    "rolling_prev_match_behinds_min",
    "rolling_prev_match_behinds_skew",
    "rolling_prev_match_behinds_std",
    "rolling_prev_match_hit_outs_sum",
    "rolling_prev_match_hit_outs_max",
    "rolling_prev_match_hit_outs_min",
    "rolling_prev_match_hit_outs_skew",
    "rolling_prev_match_hit_outs_std",
    "rolling_prev_match_tackles_sum",
    "rolling_prev_match_tackles_max",
    "rolling_prev_match_tackles_min",
    "rolling_prev_match_tackles_skew",
    "rolling_prev_match_tackles_std",
    "rolling_prev_match_rebounds_sum",
    "rolling_prev_match_rebounds_max",
    "rolling_prev_match_rebounds_min",
    "rolling_prev_match_rebounds_skew",
    "rolling_prev_match_rebounds_std",
    "rolling_prev_match_inside_50s_sum",
    "rolling_prev_match_inside_50s_max",
    "rolling_prev_match_inside_50s_min",
    "rolling_prev_match_inside_50s_skew",
    "rolling_prev_match_inside_50s_std",
    "rolling_prev_match_clearances_sum",
    "rolling_prev_match_clearances_max",
    "rolling_prev_match_clearances_min",
    "rolling_prev_match_clearances_skew",
    "rolling_prev_match_clearances_std",
    "rolling_prev_match_clangers_sum",
    "rolling_prev_match_clangers_max",
    "rolling_prev_match_clangers_min",
    "rolling_prev_match_clangers_skew",
    "rolling_prev_match_clangers_std",
    "rolling_prev_match_frees_for_sum",
    "rolling_prev_match_frees_for_max",
    "rolling_prev_match_frees_for_min",
    "rolling_prev_match_frees_for_skew",
    "rolling_prev_match_frees_for_std",
    "rolling_prev_match_frees_against_sum",
    "rolling_prev_match_frees_against_max",
    "rolling_prev_match_frees_against_min",
    "rolling_prev_match_frees_against_skew",
    "rolling_prev_match_frees_against_std",
    "rolling_prev_match_contested_possessions_sum",
    "rolling_prev_match_contested_possessions_max",
    "rolling_prev_match_contested_possessions_min",
    "rolling_prev_match_contested_possessions_skew",
    "rolling_prev_match_contested_possessions_std",
    "rolling_prev_match_uncontested_possessions_sum",
    "rolling_prev_match_uncontested_possessions_max",
    "rolling_prev_match_uncontested_possessions_min",
    "rolling_prev_match_uncontested_possessions_skew",
    "rolling_prev_match_uncontested_possessions_std",
    "rolling_prev_match_contested_marks_sum",
    "rolling_prev_match_contested_marks_max",
    "rolling_prev_match_contested_marks_min",
    "rolling_prev_match_contested_marks_skew",
    "rolling_prev_match_contested_marks_std",
    "rolling_prev_match_marks_inside_50_sum",
    "rolling_prev_match_marks_inside_50_max",
    "rolling_prev_match_marks_inside_50_min",
    "rolling_prev_match_marks_inside_50_skew",
    "rolling_prev_match_marks_inside_50_std",
    "rolling_prev_match_one_percenters_sum",
    "rolling_prev_match_one_percenters_max",
    "rolling_prev_match_one_percenters_min",
    "rolling_prev_match_one_percenters_skew",
    "rolling_prev_match_one_percenters_std",
    "rolling_prev_match_bounces_sum",
    "rolling_prev_match_bounces_max",
    "rolling_prev_match_bounces_min",
    "rolling_prev_match_bounces_skew",
    "rolling_prev_match_bounces_std",
    "rolling_prev_match_goal_assists_sum",
    "rolling_prev_match_goal_assists_max",
    "rolling_prev_match_goal_assists_min",
    "rolling_prev_match_goal_assists_skew",
    "rolling_prev_match_goal_assists_std",
    "rolling_prev_match_time_on_ground_sum",
    "rolling_prev_match_time_on_ground_max",
    "rolling_prev_match_time_on_ground_min",
    "rolling_prev_match_time_on_ground_skew",
    "rolling_prev_match_time_on_ground_std",
    "last_year_brownlow_votes_sum",
    "last_year_brownlow_votes_max",
    "last_year_brownlow_votes_min",
    "last_year_brownlow_votes_skew",
    "last_year_brownlow_votes_std",
    "oppo_rolling_prev_match_kicks_sum",
    "oppo_rolling_prev_match_kicks_max",
    "oppo_rolling_prev_match_kicks_min",
    "oppo_rolling_prev_match_kicks_skew",
    "oppo_rolling_prev_match_kicks_std",
    "oppo_rolling_prev_match_marks_sum",
    "oppo_rolling_prev_match_marks_max",
    "oppo_rolling_prev_match_marks_min",
    "oppo_rolling_prev_match_marks_skew",
    "oppo_rolling_prev_match_marks_std",
    "oppo_rolling_prev_match_handballs_sum",
    "oppo_rolling_prev_match_handballs_max",
    "oppo_rolling_prev_match_handballs_min",
    "oppo_rolling_prev_match_handballs_skew",
    "oppo_rolling_prev_match_handballs_std",
    "oppo_rolling_prev_match_goals_sum",
    "oppo_rolling_prev_match_goals_max",
    "oppo_rolling_prev_match_goals_min",
    "oppo_rolling_prev_match_goals_skew",
    "oppo_rolling_prev_match_goals_std",
    "oppo_rolling_prev_match_behinds_sum",
    "oppo_rolling_prev_match_behinds_max",
    "oppo_rolling_prev_match_behinds_min",
    "oppo_rolling_prev_match_behinds_skew",
    "oppo_rolling_prev_match_behinds_std",
    "oppo_rolling_prev_match_hit_outs_sum",
    "oppo_rolling_prev_match_hit_outs_max",
    "oppo_rolling_prev_match_hit_outs_min",
    "oppo_rolling_prev_match_hit_outs_skew",
    "oppo_rolling_prev_match_hit_outs_std",
    "oppo_rolling_prev_match_tackles_sum",
    "oppo_rolling_prev_match_tackles_max",
    "oppo_rolling_prev_match_tackles_min",
    "oppo_rolling_prev_match_tackles_skew",
    "oppo_rolling_prev_match_tackles_std",
    "oppo_rolling_prev_match_rebounds_sum",
    "oppo_rolling_prev_match_rebounds_max",
    "oppo_rolling_prev_match_rebounds_min",
    "oppo_rolling_prev_match_rebounds_skew",
    "oppo_rolling_prev_match_rebounds_std",
    "oppo_rolling_prev_match_inside_50s_sum",
    "oppo_rolling_prev_match_inside_50s_max",
    "oppo_rolling_prev_match_inside_50s_min",
    "oppo_rolling_prev_match_inside_50s_skew",
    "oppo_rolling_prev_match_inside_50s_std",
    "oppo_rolling_prev_match_clearances_sum",
    "oppo_rolling_prev_match_clearances_max",
    "oppo_rolling_prev_match_clearances_min",
    "oppo_rolling_prev_match_clearances_skew",
    "oppo_rolling_prev_match_clearances_std",
    "oppo_rolling_prev_match_clangers_sum",
    "oppo_rolling_prev_match_clangers_max",
    "oppo_rolling_prev_match_clangers_min",
    "oppo_rolling_prev_match_clangers_skew",
    "oppo_rolling_prev_match_clangers_std",
    "oppo_rolling_prev_match_frees_for_sum",
    "oppo_rolling_prev_match_frees_for_max",
    "oppo_rolling_prev_match_frees_for_min",
    "oppo_rolling_prev_match_frees_for_skew",
    "oppo_rolling_prev_match_frees_for_std",
    "oppo_rolling_prev_match_frees_against_sum",
    "oppo_rolling_prev_match_frees_against_max",
    "oppo_rolling_prev_match_frees_against_min",
    "oppo_rolling_prev_match_frees_against_skew",
    "oppo_rolling_prev_match_frees_against_std",
    "oppo_rolling_prev_match_contested_possessions_sum",
    "oppo_rolling_prev_match_contested_possessions_max",
    "oppo_rolling_prev_match_contested_possessions_min",
    "oppo_rolling_prev_match_contested_possessions_skew",
    "oppo_rolling_prev_match_contested_possessions_std",
    "oppo_rolling_prev_match_uncontested_possessions_sum",
    "oppo_rolling_prev_match_uncontested_possessions_max",
    "oppo_rolling_prev_match_uncontested_possessions_min",
    "oppo_rolling_prev_match_uncontested_possessions_skew",
    "oppo_rolling_prev_match_uncontested_possessions_std",
    "oppo_rolling_prev_match_contested_marks_sum",
    "oppo_rolling_prev_match_contested_marks_max",
    "oppo_rolling_prev_match_contested_marks_min",
    "oppo_rolling_prev_match_contested_marks_skew",
    "oppo_rolling_prev_match_contested_marks_std",
    "oppo_rolling_prev_match_marks_inside_50_sum",
    "oppo_rolling_prev_match_marks_inside_50_max",
    "oppo_rolling_prev_match_marks_inside_50_min",
    "oppo_rolling_prev_match_marks_inside_50_skew",
    "oppo_rolling_prev_match_marks_inside_50_std",
    "oppo_rolling_prev_match_one_percenters_sum",
    "oppo_rolling_prev_match_one_percenters_max",
    "oppo_rolling_prev_match_one_percenters_min",
    "oppo_rolling_prev_match_one_percenters_skew",
    "oppo_rolling_prev_match_one_percenters_std",
    "oppo_rolling_prev_match_bounces_sum",
    "oppo_rolling_prev_match_bounces_max",
    "oppo_rolling_prev_match_bounces_min",
    "oppo_rolling_prev_match_bounces_skew",
    "oppo_rolling_prev_match_bounces_std",
    "oppo_rolling_prev_match_goal_assists_sum",
    "oppo_rolling_prev_match_goal_assists_max",
    "oppo_rolling_prev_match_goal_assists_min",
    "oppo_rolling_prev_match_goal_assists_skew",
    "oppo_rolling_prev_match_goal_assists_std",
    "oppo_rolling_prev_match_time_on_ground_sum",
    "oppo_rolling_prev_match_time_on_ground_max",
    "oppo_rolling_prev_match_time_on_ground_min",
    "oppo_rolling_prev_match_time_on_ground_skew",
    "oppo_rolling_prev_match_time_on_ground_std",
    "oppo_last_year_brownlow_votes_sum",
    "oppo_last_year_brownlow_votes_max",
    "oppo_last_year_brownlow_votes_min",
    "oppo_last_year_brownlow_votes_skew",
    "oppo_last_year_brownlow_votes_std",
    "goals",
    "behinds",
    "score",
    "oppo_goals",
    "oppo_behinds",
    "oppo_score",
    "year",
    "round_number",
    "at_home",
    "out_of_state",
    "travel_distance",
    "result",
    "margin",
    "prev_match_score",
    "prev_match_oppo_score",
    "prev_match_result",
    "prev_match_margin",
    "prev_match_goals",
    "prev_match_behinds",
    "cum_win_points",
    "win_streak",
    "elo_rating",
    "rolling_prev_match_result_rate",
    "rolling_mean_margin_by_oppo_team",
    "rolling_mean_result_by_oppo_team",
    "rolling_mean_score_by_oppo_team",
    "rolling_mean_margin_by_venue",
    "rolling_mean_result_by_venue",
    "rolling_mean_score_by_venue",
    "oppo_travel_distance",
    "oppo_prev_match_score",
    "oppo_prev_match_oppo_score",
    "oppo_prev_match_result",
    "oppo_prev_match_margin",
    "oppo_prev_match_goals",
    "oppo_prev_match_behinds",
    "oppo_cum_win_points",
    "oppo_win_streak",
    "oppo_elo_rating",
    "oppo_rolling_prev_match_result_rate",
    "oppo_rolling_mean_margin_by_oppo_team",
    "oppo_rolling_mean_result_by_oppo_team",
    "oppo_rolling_mean_score_by_oppo_team",
    "oppo_rolling_mean_margin_by_venue",
    "oppo_rolling_mean_result_by_venue",
    "oppo_rolling_mean_score_by_venue",
    "cum_percent",
    "ladder_position",
    "elo_pred_win",
    "rolling_elo_pred_win_rate",
    "elo_rating_divided_by_ladder_position",
    "oppo_cum_percent",
    "oppo_ladder_position",
    "elo_rating_divided_by_win_odds",
    "win_odds_multiplied_by_ladder_position",
]
